week6/day3/afternoon_review/blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about', as: 'about'
  get 'category/:name', to: 'welcome#category', as: 'category'

  resources :posts
  resources :comments

  root 'welcome#index'
end

week6/day3/afternoon_review/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "New Post successfully created"
    else
      flash[:alert] = "Error Occured"
      render :new
    end
  end

  def edit; end
  def update; end
  def destroy; end

  private
  def post_params
    params.require(:post).permit(:title, :body, :category)
  end
end

week6/day3/afternoon_review/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class='main'>
    <h1><%= link_to 'My Awesome Site', root_path %></h1>
    <nav>
      <%= link_to 'Posts', posts_path %>
      <%= link_to 'About', about_path %>
    </nav>
  </header>
  <div class='container'>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, { class: name }) %>
    <% end %>
    <%= yield %>
  </div>
  <footer>
    <%= params.inspect if Rails.env.development? %>
    Made by justin
  </footer>
</body>
</html>

week6/day3/afternoon_review/blog/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

week6/day3/afternoon_review/blog/app/views/posts/show.html.erb
<article>
  <header>
    <h1><%= @post.title %></h1>
    <small><%= @post.category %></small>
  </header>
  <p>
    <%= raw @post.body %>
  </p>
  <footer>
    <div class='actions'>
      <%= link_to 'All Posts', posts_path %>
    </div>
  </footer>
</article>

<section class='comments'>
  <h3> Comments (<%= @post.comments.count %>) </h3>
  <%= form_for(@comment) do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit "New Comment" %>
  <% end %>
  <ul>
    <% @post.comments.each do |comment| %>
      <li>
        <strong><%= comment.username %></strong>:
        <%= comment.body %>
      </li>
    <% end %>
  </ul>
</section>